// Mocks generated by Mockito 5.4.6 from annotations
// in canadapp/test/mocks/gestione_certificato_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:canadapp/data/repositories/gestione_certificato_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GestioneCertificatoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGestioneCertificatoRepository extends _i1.Mock
    implements _i2.GestioneCertificatoRepository {
  MockGestioneCertificatoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>> fetchCertificate(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCertificate, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> uploadCertificate(
    String? userId,
    _i4.File? file,
    String? dataScadenza,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadCertificate, [userId, file, dataScadenza]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> getCertificatoUrl(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCertificatoUrl, [userId]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#getCertificatoUrl, [userId]),
              ),
            ),
          )
          as _i3.Future<String>);
}
